version: 0.0
os: linux
files:
  - source: index.html
    destination: /usr/share/nginx/html
hooks:
  BeforeInstall:
    - location: scripts/install-nginx.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start-nginx.sh
      timeout: 60
      runas: root
