version: 0.2

phases:
  install:
    commands:
      - echo "Installing test tools"
  build:
    commands:
      - echo "Running tests"
      - test -f index.html
artifacts:
  files:
    - index.html
    - deployspec.yml
    - scripts/**/*
